package com.shand1an.sreln.screen;

/** ponytail: huge static data arrays — song lyrics + ASCII art embedded in code */
public class SongData {

    public static final String[][] ASCII_ART = {
        { // 0
            "              .,-:;//;:=,               ",
            "          . :H@@@MM@M#H/.,+%;,          ",
            "       ,/X+ +M@@M@MM%=,-%HMMM@X/,       ",
            "     -+@MM; #M@@MH+-,;XMMMM@MMMM@+-     ",
            "    ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.   ",
            "  ,%MM@@MH ,@%=            .---=-=:=,.  ",
            "  =@#@@@MX .,              -%HX##%%%+;  ",
            " =-./@M@M$                  .;@MMMM@MM: ",
            " X@/ -#MM/                    .+MM@@@M$ ",
            ",@M@H: :@:                    . =X#@@@@-",
            ",@@@MMX, .                    /H- ;@M@M=",
            ".H@@@@M@+,                    %MM+..%#$.",
            " /MMMM@MMH/.                  XM@MH; =; ",
            "  /%+%#XHH@$=              , .H@@@@MX,  ",
            "   .=--------.           -%H.,@@@@@MX,  ",
            "   .%MM@@@HHHXX###%+= .:#MMX =M@@MM%.   ",
            "     =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=     ",
            "       =%@M@M#@$-.=#@MM@@@M; %M%=       ",
            "         ,:+$+-,/H#MMMMMMM@= =,         ",
            "               =++%%%%+/:-.             ",
        },
        { // 1
            "             =+$HM####@H%;,             ",
            "          /H###############M$,          ",
            "          ,@################+           ",
            "           .H##############+            ",
            "             X############/             ",
            "              $##########/              ",
            "               %########/               ",
            "                /X/;;+X/                ",
            "                 -XHHX-                 ",
            "                ,######,                ",
            "#############X  .M####M.  X#############",
            "##############-   -//-   -##############",
            "X##############%,      ,+##############X",
            "-##############X        X##############-",
            " %############%          %############% ",
            "  %##########;            ;##########%  ",
            "   ;#######M=              =M#######;   ",
            "    .+M###@,                ,@###M+.    ",
            "       :XH.                  .HX:       ",
            "                                        ",
        },
        { // 2
            "                 =/;;/-                 ",
            "                +:    //                ",
            "               /;      /;               ",
            "              -X        H.              ",
            ".//;;;:;;-,   X=        :+   .-;:=;:;%;.",
            "M-       ,=;;;#:,      ,:#;;:=,       ,@",
            ":%           :%.=/++++/=.$=           %=",
            " ,%;         %/:+/;,,/++:+/         ;+. ",
            "   ,+/.    ,;@+,        ,%H;,    ,/+,   ",
            "      ;+;;/= @.  .H##X   -X :///+;      ",
            "      ;+=;;;.@,  .XM@$.  =X.//;=%/.     ",
            "   ,;:      :@%=        =$H:     .+%-   ",
            " ,%=         %;-///==///-//         =%, ",
            ";+           :%-;;;:;;;;-X-           +:",
            "@-      .-;;;;M-        =M/;;;-.      -X",
            " :;;::;;-.    %-        :+    ,-;;-;:== ",
            "              ,X        H.              ",
            "               ;/      %=               ",
            "                //    +;                ",
            "                 ,////,                 ",
        },
        { // 3
            "                          .,---.        ",
            "                        ,/XM#MMMX;,     ",
            "                      -%##########M%,   ",
            "                     -@######%  $###@=  ",
            "      .,--,         -H#######$   $###M: ",
            "   ,;$M###MMX;     .;##########$;HM###X=",
            " ,/@##########H=      ;################+",
            "-+#############M/,      %##############+",
            "%M###############=      /##############:",
            "H################      .M#############;.",
            "@###############M      ,@###########M:. ",
            "X################,      -$=X#######@:   ",
            "/@##################%-     +######$-    ",
            ".;##################X     .X#####+,     ",
            " .;H################/     -X####+.      ",
            "   ,;X##############,       .MM/        ",
            "      ,:+$H@M#######M#$-    .$$=        ",
            "           .,-=;+$@###X:    ;/=.        ",
            "                  .,/X$;   .::,         ",
            "                      .,    ..          ",
        },
        { // 4
            "            .+                          ",
            "             /M;                        ",
            "              H#@:              ;,      ",
            "              -###H-          -@/       ",
            "               %####$.  -;  .%#X        ",
            "                M#####+;#H :M#M.        ",
            "..          .+/;%#########X###-         ",
            " -/%H%+;-,    +##############/          ",
            "    .:$M###MH$%+############X  ,--=;-   ",
            "        -/H#####################H+=.    ",
            "           .+#################X.        ",
            "         =%M####################H;.     ",
            "            /@###############+;;/%%;,   ",
            "         -%###################$.        ",
            "       ;H######################M=       ",
            "    ,%#####MH$%;+#####M###-/@####%      ",
            "  :$H%+;=-      -####X.,H#   -+M##@-    ",
            " .              ,###;    ;      =$##+   ",
            "                .#H,               :XH, ",
            "                 +                   .;-",
        },
        { // 5
            "                     -$-                ",
            "                    .H##H,              ",
            "                   +######+             ",
            "                .+#########H.           ",
            "              -$############@.          ",
            "            =H###############@  -X:     ",
            "          .$##################:  @#@-   ",
            "     ,;  .M###################;  H###;  ",
            "   ;@#:  @###################@  ,#####: ",
            " -M###.  M#################@.  ;######H ",
            " M####-  +###############$   =@#######X ",
            " H####$   -M###########+   :#########M, ",
            "  /####X-   =########%   :M########@/.  ",
            "    ,;%H@X;   .$###X   :##MM@%+;:-      ",
            "                 ..                     ",
            "  -/;:-,.              ,,-==+M########H ",
            " -##################@HX%%+%%$%%%+:,,    ",
            "   .-/H%%%+%%$H@###############M@+=:/+: ",
            "/XHX%:#####MH%=    ,---:;;;;/%%XHM,:###$",
            "$@#MX %+;-                           .  ",
        },
        { // 6
            "                                     :X-",
            "                                  :X### ",
            "                                ;@####@ ",
            "                              ;M######X ",
            "                            -@########$ ",
            "                          .$##########@ ",
            "                         =M############-",
            "                        +##############$",
            "                      .H############$=. ",
            "         ,/:         ,M##########M;.    ",
            "      -+@###;       =##########M;       ",
            "   =%M#######;     :#########M/         ",
            "-$M###########;   :#########/           ",
            " ,;X###########; =########$.            ",
            "     ;H#########+#######M=              ",
            "       ,+##############+                ",
            "          /M#########@-                 ",
            "            ;M######%                   ",
            "              +####:                    ",
            "               ,$M-                     ",
        },
        { // 7
            "           .-;+$XHHHHHHX$+;-.           ",
            "        ,;X@@X%/;=----=:/%X@@X/,        ",
            "      =$@@%=.              .=+H@X:      ",
            "    -XMX:                      =XMX=    ",
            "   /@@:                          =H@+   ",
            "  %@X,                            .$@$  ",
            " +@X.                               $@% ",
            "-@@,                                .@@=",
            "%@%                                  +@$",
            "H@:                                  :@H",
            "H@:         :HHHHHHHHHHHHHHHHHHX,    =@H",
            "%@%         ;@M@@@@@@@@@@@@@@@@@H-   +@$",
            "=@@,        :@@@@@@@@@@@@@@@@@@@@@= .@@:",
            " +@X        :@@@@@@@@@@@@@@@M@@@@@@:%@% ",
            "  $@$,      ;@@@@@@@@@@@@@@@@@M@@@@@@$. ",
            "   +@@HHHHHHH@@@@@@@@@@@@@@@@@@@@@@@+   ",
            "    =X@@@@@@@@@@@@@@@@@@@@@@@@@@@@X=    ",
            "      :$@@@@@@@@@@@@@@@@@@@M@@@@$:      ",
            "        ,;$@@@@@@@@@@@@@@@@@@X/-        ",
            "           .-;+$XXHHHHHX$+;-.           ",
        },
        { // 8
            "            ,:/+/-                      ",
            "            /M/              .,-=;//;-  ",
            "       .:/= ;MH/,    ,=/+%$XH@MM#@:     ",
            "      -$##@+$###@H@MMM#######H:.    -/H#",
            " .,H@H@ X######@ -H#####@+-     -+H###@ ",
            "  .,@##H;      +XM##M/,     =%@###@X;-  ",
            "X%-  :M##########$.    .:%M###@%:       ",
            "M##H,   +H@@@$/-.  ,;$M###@%,          -",
            "M####M=,,---,.-%%H####M$:          ,+@##",
            "@##################@/.         :%H##@$- ",
            "M###############H,         ;HM##M$=     ",
            "#################.    .=$M##M$=         ",
            "################H..;XM##M$=          .:+",
            "M###################@%=           =+@MH%",
            "@################M/.          =+H#X%=   ",
            "=+M##############M,       -/X#X+;.      ",
            "  .;XM##########H=    ,/X#H+:,          ",
            "     .=+HM######M+/+HM@+=.              ",
            "         ,:/%XM####H/.                  ",
            "              ,.:=-.                    ",
        },
        { // 9
            "       #+ @      # #              M#@   ",
            " .    .X  X.%##@;# #   +@#######X. @#%  ",
            "   ,==.   ,######M+  -#####%M####M-    #",
            "  :H##M%:=##+ .M##M,;#####/+#######% ,M#",
            " .M########=  =@#@.=#####M=M#######=  X#",
            " :@@MMM##M.  -##M.,#######M#######. =  M",
            "             @##..###:.    .H####. @@ X,",
            "   ############: ###,/####;  /##= @#. M ",
            "           ,M## ;##,@#M;/M#M  @# X#% X# ",
            ".%=   ######M## ##.M#:   ./#M ,M #M ,#$ ",
            "##/         $## #+;#: #### ;#/ M M- @# :",
            "#+ #M@MM###M-;M #:$#-##$H# .#X @ + $#. #",
            "      ######/.: #%=# M#:MM./#.-#  @#: H#",
            "+,.=   @###: /@ %#,@  ##@X #,-#@.##% .@#",
            "#####+;/##/ @##  @#,+       /#M    . X, ",
            "   ;###M#@ M###H .#M-     ,##M  ;@@; ###",
            "   .M#M##H ;####X ,@#######M/ -M###$  -H",
            "    .M###%  X####H  .@@MM@;  ;@#M@      ",
            "      H#M    /@####/      ,++.  / ==-,  ",
            "               ,=/:, .+X@MMH@#H  #####$=",
        },
    };

    public static final SongLyric[] LYRICS = {
        new SongLyric("Forms FORM-29827281-12:", 0, -1, 0),
        new SongLyric("Test Assessment Report", 200, -1, 0),
        new SongLyric("\u0000\u0000\u0000\u0000\u0000\u0000\u0000", 400, -1, 0),
        new SongLyric("", 710, 0, 4),
        new SongLyric("This was a triumph.", 730, 2, 0),
        new SongLyric("", 930, 0, 5),
        new SongLyric("I'm making a note here:", 1123, 2, 0),
        new SongLyric("HUGE SUCCESS.", 1347, 1.7, 0),
        new SongLyric("It's hard to overstate", 1627, -1, 0),
        new SongLyric("my satisfaction.", 1873, 2.6, 0),
        new SongLyric("Aperture Science", 2350, 1.8, 0),
        new SongLyric("0", 2350, 0, 2),
        new SongLyric("We do what we must", 2733, 1.6, 0),
        new SongLyric("because we can.", 2910, 1.5, 0),
        new SongLyric("For the good of all of us.", 3237, -1, 0),
        new SongLyric("1", 3500, 0, 2),
        new SongLyric("Except the ones who are dead.", 3567, -1, 0),
        new SongLyric("", 3717, 0.05, 0),
        new SongLyric("0", 3717, 0, 2),
        new SongLyric("But there's no sense crying", 3787, -1, 0),
        new SongLyric("over every mistake.", 3973, 1.77, 0),
        new SongLyric("You just keep on trying", 4170, -1, 0),
        new SongLyric("till you run out of cake.", 4370, -1, 0),
        new SongLyric("2", 4500, 0, 2),
        new SongLyric("And the Science gets done.", 4570, -1, 0),
        new SongLyric("And you make a neat gun.", 4767, -1, 0),
        new SongLyric("0", 4903, 0, 2),
        new SongLyric("For the people who are", 4973, -1, 0),
        new SongLyric("still alive.", 5110, 1.6, 1),
        new SongLyric("0", 5353, 0, 3),
        new SongLyric("Forms FORM-55551-5:", 5413, -1, 0),
        new SongLyric("Personnel File Addendum:", 5477, 1.13, 0),
        new SongLyric("", 5650, 0.05, 0),
        new SongLyric("Dear <<Subject Name Here>>,", 5650, -1, 0),
        new SongLyric("", 5900, -1, 0),
        new SongLyric("I'm not even angry.", 5900, 1.86, 0),
        new SongLyric("I'm being ", 6320, -1, 1),
        new SongLyric("so ", 6413, -1, 1),
        new SongLyric("sincere right now.", 6470, 1.9, 0),
        new SongLyric("Even though you broke ", 6827, -1, 1),
        new SongLyric("3", 7020, 0, 2),
        new SongLyric("my heart.", 7090, -1, 0),
        new SongLyric("And killed me.", 7170, 1.43, 0),
        new SongLyric("4", 7300, 0, 2),
        new SongLyric("And tore me to pieces.", 7500, 1.83, 0),
        new SongLyric("And threw every piece ", 7900, -1, 1),
        new SongLyric("into a fire.", 8080, 1.8, 0),
        new SongLyric("5", 8080, 0, 2),
        new SongLyric("As they burned it hurt because", 8430, -1, 0),
        new SongLyric("6", 8690, 0, 2),
        new SongLyric("I was so happy for you!", 8760, 1.67, 0),
        new SongLyric("Now, these points of data", 8960, -1, 0),
        new SongLyric("make a beautiful line.", 9167, -1, 0),
        new SongLyric("And we're out of beta.", 9357, -1, 0),
        new SongLyric("We're releasing on time.", 9560, -1, 0),
        new SongLyric("4", 9700, 0, 2),
        new SongLyric("So I'm GLaD I got burned.", 9770, -1, 0),
        new SongLyric("2", 9913, 0, 2),
        new SongLyric("Think of all the things we learned", 9983, -1, 0),
        new SongLyric("0", 10120, 0, 2),
        new SongLyric("For the people who are", 10190, -1, 0),
        new SongLyric("Still alive.", 10327, 1.8, 0),
        new SongLyric("0", 10603, 0, 3),
        new SongLyric("Forms FORM-55551-6:", 10663, -1, 0),
        new SongLyric("Personnel File Addendum Addendum:", 10710, 1.36, 0),
        new SongLyric("", 10710, 0.05, 0),
        new SongLyric("One last thing:", 10910, -1, 0),
        new SongLyric("", 11130, 0.05, 0),
        new SongLyric("Go ahead and leave ", 11130, -1, 1),
        new SongLyric("me.", 11280, 0.5, 0),
        new SongLyric("I think I'd prefer to stay ", 11507, -1, 1),
        new SongLyric("inside.", 11787, 1.13, 0),
        new SongLyric("Maybe you'll find someone else", 12037, -1, 0),
        new SongLyric("To help you.", 12390, 1.23, 0),
        new SongLyric("Maybe Black ", 12737, -1, 1),
        new SongLyric("7", 12787, 0, 2),
        new SongLyric("Mesa...", 12857, 2.7, 0),
        new SongLyric("THAT WAS A JOKE.", 13137, 1.46, 1),
        new SongLyric(" FAT CHANCE.", 13387, 1.1, 0),
        new SongLyric("Anyway, ", 13620, -1, 1),
        new SongLyric("8", 13670, 0, 2),
        new SongLyric("this cake is great.", 13740, -1, 0),
        new SongLyric("It's so delicious and moist.", 13963, -1, 0),
        new SongLyric("9", 14123, 0, 2),
        new SongLyric("Look at me still talking", 14193, -1, 0),
        new SongLyric("1", 14320, 0, 2),
        new SongLyric("when there's science to do.", 14390, -1, 0),
        new SongLyric("0", 14527, 0, 2),
        new SongLyric("When I look out there,", 14597, -1, 0),
        new SongLyric("It makes me GLaD I'm not you.", 14767, -1, 0),
        new SongLyric("2", 14913, 0, 2),
        new SongLyric("I've experiments to run.", 14983, -1, 0),
        new SongLyric("4", 15120, 0, 2),
        new SongLyric("There is research to be done.", 15190, -1, 0),
        new SongLyric("0", 15320, 0, 2),
        new SongLyric("On the people who are", 15390, -1, 0),
        new SongLyric("still alive", 15553, 2.0, 1),
        new SongLyric("0", 15697, 0, 3),
        new SongLyric("", 15757, 0.05, 0),
        new SongLyric("", 15757, 0.05, 0),
        new SongLyric("", 15757, 0.05, 0),
        new SongLyric("PS: And believe me I am", 15757, -1, 0),
        new SongLyric("still alive.", 15960, 1.13, 0),
        new SongLyric("PPS: I'm doing Science and I'm", 16150, -1, 0),
        new SongLyric("still alive.", 16363, 1.13, 0),
        new SongLyric("PPPS: I feel FANTASTIC and I'm", 16550, -1, 0),
        new SongLyric("still alive.", 16760, -1, 0),
        new SongLyric("", 16860, -1, 0),
        new SongLyric("FINAL THOUGH:", 16860, -1, 0),
        new SongLyric("While you're dying I'll be", 16993, -1, 0),
        new SongLyric("still alive.", 17157, -1, 0),
        new SongLyric("", 17277, -1, 0),
        new SongLyric("FINAL THOUGH PS:", 17277, -1, 0),
        new SongLyric("And when you're dead I will be", 17367, -1, 0),
        new SongLyric("still alive.", 17550, 1.13, 0),
        new SongLyric("", 17550, -1, 0),
        new SongLyric("", 17550, 0.05, 0),
        new SongLyric("STILL ALIVE", 17760, 1.13, 0),
        new SongLyric("0", 17900, 0, 3),
        new SongLyric("0", 18500, 0, 3),
        new SongLyric("ENDENDENDENDENDENDENDEND", 18500, 0.05, 9),
    };

    public static final String CREDITS = ">LIST PERSONNEL\n\n"
        + "  Gautam Babbar\n  Ted Backman\n  Kelly Bailey\n  Jeff Ballinger\n"
        + "  Aaron Barber\n  Jeep Barnett\n  Jeremy Bennett\n  Dan Berger\n"
        + "  Yahn Bernier\n  Ken Birdwell\n  Derrick Birum\n  Mike Blaszczak\n"
        + "  Iestyn Bleasdale-Shepherd\n  Chris Bokitch\n  Steve Bond\n"
        + "  Matt Boone\n  Antoine Bourdon\n  Jamaal Bradley\n  Jason Brashill\n"
        + "  Charlie Brown\n  Charlie Burgin\n  Andrew Burke\n  Augusta Butlin\n"
        + "  Julie Caldwell\n  Dario Casali\n  Chris Chin\n  Jess Cliffe\n"
        + "  Phil Co\n  John Cook\n  Christen Coomer\n  Greg Coomer\n"
        + "  Scott Dalton\n  Kerry Davis\n  Jason Deakins\n  Joe Demers\n"
        + "  Ariel Diaz\n  Quintin Doroquez\n  Jim Dose\n  Chris Douglass\n"
        + "  Laura Dubuk\n  Mike Dunkle\n  Mike Durand\n  Mike Dussault\n"
        + "  Dhabih Eng\n  Katie Engel\n  Chet Faliszek\n  Adrian Finol\n"
        + "  Bill Fletcher\n  Moby Francke\n  Stephane Gaudette\n  Kathy Gehrig\n"
        + "  Vitaliy Genkin\n  Paul Graham\n  Chris Green\n  Chris Grinstead\n"
        + "  John Guthrie\n  Aaron Halifax\n  Reagan Halifax\n  Leslie Hall\n"
        + "  Jeff Hameluck\n  Joe Han\n  Don Holden\n  Jason Holtman\n"
        + "  Gray Horsfield\n  Keith Huggins\n  Jim Hughes\n  Jon Huisingh\n"
        + "  Brian Jacobson\n  Lars Jensvold\n  Erik Johnson\n  Jakob Jungels\n"
        + "  Rich Kaethler\n  Steve Kalning\n  Aaron Kearly\n  Iikka Keranen\n"
        + "  David Kircher\n  Eric Kirchmer\n  Scott Klintworth\n  Alden Kroll\n"
        + "  Marc Laidlaw\n  Jeff Lane\n  Tim Larkin\n  Dan LeFree\n"
        + "  Isabelle LeMay\n  Tom Leonard\n  Jeff Lind\n  Doug Lombardi\n"
        + "  Bianca Loomis\n  Richard Lord\n  Realm Lovejoy\n  Randy Lundeen\n"
        + "  Scott Lynch\n  Ido Magal\n  Nick Maggiore\n  John McCaskey\n"
        + "  Patrick McClard\n  Steve McClure\n  Hamish McKenzie\n  Gary McTaggart\n"
        + "  Jason Mitchell\n  Mike Morasky\n  John Morello II\n  Bryn Moslow\n"
        + "  Arsenio Navarro\n  Gabe Newell\n  Milton Ngan\n  Jake Nicholson\n"
        + "  Martin Otten\n  Nick Papineau\n  Karen Prell\n  Bay Raitt\n"
        + "  Tristan Reidford\n  Alfred Reynolds\n  Matt Rhoten\n  Garret Rickey\n"
        + "  Dave Riller\n  Elan Ruskin\n  Matthew Russell\n  Jason Ruymen\n"
        + "  David Sawyer\n  Marc Scaparro\n  Wade Schin\n  Matthew Scott\n"
        + "  Aaron Seeler\n  Jennifer Seeley\n  Taylor Sherman\n  Eric Smith\n"
        + "  Jeff Sorensen\n  David Speyrer\n  Jay Stelly\n  Jeremy Stone\n"
        + "  Eric Strand\n  Kim Swift\n  Kelly Thornton\n  Eric Twelker\n"
        + "  Carl Uhlman\n  Doug Valente\n  Bill Van Buren\n  Gabe Van Engel\n"
        + "  Alex Vlachos\n  Robin Walker\n  Joshua Weier\n  Andrea Wicklund\n"
        + "  Greg Winkler\n  Erik Wolpaw\n  Doug Wood\n  Matt T. Wood\n"
        + "  Danika Wright\n  Matt Wright\n  Shawn Zabecki\n  Torsten Zabka\n\n\n"
        + "  'Still Alive' by:\n  Jonathan Coulton\n\n"
        + "  Voices:\n  Ellen McLain - GlaDOS, Turrets\n"
        + "  Mike Patton - THE ANGER SPHERE\n\n"
        + "  Voice Casting:\n  Shana Landsburg / Teri Fiddleman\n\n"
        + "  Voice Recording:\n  Pure Audio, Seattle, WA\n\n"
        + "  Voice recording scheduling and logistics:\n"
        + "  Pat Cockburn, Pure Audio\n\n"
        + "  Translations:\n  SDL\n\n"
        + "  Crack Legal Team:\n  Liam Lavery\n  Karl Quackenbush\n"
        + "  Kristen Boraas\n  Kevin Rosenfield\n  Alan Bruggeman\n"
        + "  Dennis Tessier\n\n"
        + "  Thanks for the use of their face:\n  Alesia Glidewell - Chell\n\n"
        + "  Special thanks to everyone at:\n"
        + "  Alienware\n  ATI\n  Dell\n  Falcon Northwest\n"
        + "  Havok\n  SOFTIMAGE\n"
        + "  and Don Kemmis, SLK Technologies\n\n\n"
        + "  THANK YOU FOR PARTICIPATING\n  IN THIS\n"
        + "  ENRICHMENT CENTER ACTIVITY!!\n";
}