modLoader = "javafml"
loaderVersion = "[2,)"
license = "LGPL-3.0 license"

[[mods]]
modId = "ldlib2"
version = "2.2.19"
displayName = "LowDragLib2"
authors = "KilaBash"
description = "Low Drag Lib2, a library for rendering, gui, particles, synchronize"
logoFile = "icon.png"
displayURL = "https://github.com/Low-Drag-MC/LDLib2"
issueTrackerURL = "https://github.com/Low-Drag-MC/LDLib2/issues"
[[mixins]]
config="ldlib2.mixins.json"
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.ldlib2]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1.216,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.ldlib2]]
    modId = "minecraft"
    type = "required"
    versionRange = "1.21.1"
    ordering = "NONE"
    side = "BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.ldlib2]
#openGLVersion="[3.2,)"
